[[chat]]
role = "user"
content = """
Generate a minimal C++ program that prints 'Hello, CodeScribe!' using a separate header and source file.
Include:
  - generated-src/main.cpp
  - generated-src/message.h
  - generated-src/message.cpp
  - generated-src/Makefile

Ensure each file is enclosed in <filename>...</filename> tags exactly as instructed. Add comments about the code in each file
"""
