#include <iostream>

// Fortran routines (as generated by compiler naming convention)
extern "C" {
void initialize_();
void finalize_();
void solver_();
}

int main() {
  std::cout << "C++ Driver: Serial Diffusion Example" << std::endl;

  // Initialize in Fortran
  initialize_();

  // Solve in Fortran
  solver_();
  std::cout << "C++ Driver: Simulation complete." << std::endl;

  finalize_();
  return 0;
}
