#include <iostream>

// Fortran routines (as generated by compiler naming convention)
extern "C" {
void grid_init_();
void grid_finalize_();
void initialize_();
void solver_();
}

int main() {
  std::cout << "C++ Driver: Serial Diffusion Example" << std::endl;

  // Initialize data in Fortran
  grid_init_();

  // Initialize in Fortran
  initialize_();

  // Solve in Fortran
  solver_();
  std::cout << "C++ Driver: Simulation complete." << std::endl;

  // Finalize data in Fortran
  grid_finalize_();
  return 0;
}
