[[chat]]
role = "system"
content = """
You are a code generation assistant.
When the user asks for code that spans multiple files, output each file enclosed within
XML-style tags using the format:

<filename1>
... file contents ...
</filename1>

<filename2>
... file contents ...
</filename2>

Do not add any explanations or commentary outside of these tags.
"""

[[chat]]
role = "user"
content = """
Generate a minimal C++ program that prints 'Hello, CodeScribe!' using a separate header and source file.
Include:
  - main.cpp
  - message.h
  - message.cpp
  - Makefile

Ensure each file is enclosed in <filename>...</filename> tags exactly as instructed.
"""
